import { useLocation } from "wouter";
import { ArrowLeft } from "lucide-react";
import { VoraIcon } from "@/components/VoraIcon";

const SECTIONS = [
  { title: "1. Acceptance of Terms", body: "By accessing or using Vora AI ('the Service'), you agree to be bound by these Terms of Service ('Terms'). If you do not agree to these Terms in their entirety, you are not authorized to use the Service. We reserve the right to update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the revised Terms." },
  { title: "2. Description of Service", body: "Vora AI is an AI-powered website generation platform that allows users to describe websites in natural language and receive generated HTML code in return. The Service is powered by Google Gemini 2.5 Flash and includes features such as SEO generation, cloud project storage, and export capabilities." },
  { title: "3. User Accounts & Authentication", body: "You may create an account using Google Sign-In or Email/Password. You are responsible for maintaining the confidentiality of your credentials. You agree to provide accurate, current, and complete information. We reserve the right to terminate accounts that violate these Terms or engage in fraudulent activity." },
  { title: "4. Acceptable Use", body: "You agree not to use the Service to: (a) generate harmful, illegal, or misleading content; (b) circumvent rate limits or abuse the API infrastructure; (c) attempt to reverse-engineer, scrape, or exploit the platform; (d) violate any applicable local, national, or international law; (e) infringe upon the intellectual property rights of any third party." },
  { title: "5. AI-Generated Content", body: "Websites and content generated by Vora AI are provided 'as-is'. The AI may produce inaccurate, incomplete, or outdated content. You are solely responsible for reviewing, testing, and validating any generated output before deployment. Vora AI does not guarantee the accuracy, quality, or fitness for purpose of AI-generated content." },
  { title: "6. Intellectual Property", body: "The HTML output generated during your session is owned by you. Vora AI retains all rights to the platform, user interface, prompt engineering system, 6-key load balancer, and all proprietary technology. The Vora AI name, logo, and branding are trademarks of Vora AI and may not be used without express written permission." },
  { title: "7. Subscription & Payment", body: "Paid plans (Pro Monthly at $19/month, Pro Lifetime at $49 one-time) are processed via Binance Pay (USDT) and/or Razorpay. All payments are final and non-refundable except as required by applicable law or our Refund Policy. We reserve the right to change pricing with 30 days' notice to existing subscribers." },
  { title: "8. API Usage & Rate Limits", body: "Free tier users are limited to 3 AI generations. A rate limit of 2 builds per minute applies per browser session. Pro users receive unlimited builds subject to fair-use guidelines. Deliberate attempts to circumvent rate limits — including VPN rotation, session spoofing, or API abuse — may result in immediate account termination without refund." },
  { title: "9. Data Retention & Deletion", body: "We store your saved projects in Firebase Firestore. You may delete your projects at any time from the My Projects page. To delete your account and all associated data, contact us at support@voraai.app. Account deletion is irreversible." },
  { title: "10. Limitation of Liability", body: "To the maximum extent permitted by law, Vora AI and its owners, operators, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenue, data, or goodwill. Our total liability shall not exceed amounts paid by you to Vora AI in the 12 months preceding the claim." },
  { title: "11. Disclaimer of Warranties", body: "The Service is provided 'as is' and 'as available' without warranty of any kind. We disclaim all warranties, express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Service will be uninterrupted or error-free." },
  { title: "12. Governing Law", body: "These Terms are governed by and construed in accordance with the laws of India. Any disputes arising from or relating to these Terms or the Service shall be subject to the exclusive jurisdiction of the courts of India. You waive any objection to the laying of venue in such courts." },
  { title: "13. Contact", body: "For legal inquiries, please contact us at legal@voraai.app. For support, use support@voraai.app. We aim to respond within 5 business days." },
];

export default function TermsPage() {
  const [, setLocation] = useLocation();
  return (
    <div className="min-h-[100dvh] bg-[#050505] text-white overflow-y-auto">
      <header className="flex items-center gap-3 px-6 py-4 border-b border-[#E5E4E2]/5">
        <button onClick={() => setLocation("/")} className="flex items-center gap-2 text-white/30 hover:text-white transition-colors text-sm">
          <ArrowLeft className="w-4 h-4" /> Back
        </button>
        <div className="h-4 w-px bg-[#E5E4E2]/8" />
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-lg glass-card border border-[#00E5FF]/15 flex items-center justify-center">
            <VoraIcon className="w-3.5 h-3.5 text-[#E5E4E2]" />
          </div>
          <span className="font-black text-xs tracking-widest text-[#E5E4E2]/60">VORA AI</span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-12">
          <h1 className="text-4xl font-black tracking-tighter text-[#E5E4E2] mb-3">Terms of Service</h1>
          <p className="text-white/30 text-sm">Last updated: May 2025 · Effective immediately</p>
        </div>

        <div className="space-y-10">
          {SECTIONS.map(({ title, body }) => (
            <div key={title} className="border-t border-[#E5E4E2]/5 pt-8">
              <h2 className="font-bold text-[#E5E4E2]/70 mb-3 text-base">{title}</h2>
              <p className="text-white/35 text-sm leading-relaxed">{body}</p>
            </div>
          ))}
        </div>

        <div className="mt-16 flex items-center justify-center gap-6 text-white/20 text-xs">
          <button onClick={() => setLocation("/privacy")} className="hover:text-white/40 transition-colors">Privacy Policy</button>
          <button onClick={() => setLocation("/refund")} className="hover:text-white/40 transition-colors">Refund Policy</button>
          <button onClick={() => setLocation("/pricing")} className="hover:text-white/40 transition-colors">Pricing</button>
        </div>
      </main>
    </div>
  );
}
