import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useState, useRef, useEffect } from "react";
import { Loader2, Copy, Download, Share2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { GoogleGenAI } from "@google/genai";

interface SocialCaptions {
  instagram?: string;
  twitter?: string;
  linkedin?: string;
}

export function PromoteModal({ open, onOpenChange, prompt, html, title }: { open: boolean; onOpenChange: (o: boolean) => void; prompt: string; html: string; title: string }) {
  const [captions, setCaptions] = useState<SocialCaptions | null>(null);
  const [loading, setLoading] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const { toast } = useToast();

  useEffect(() => {
    if (open && !captions && !loading) {
      generateCaptions();
    }
    if (open && canvasRef.current) {
      drawGraphic();
    }
  }, [open]);

  const generateCaptions = async () => {
    setLoading(true);
    try {
      const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
      if (!apiKey) throw new Error("Missing API key");
      
      const ai = new GoogleGenAI({ apiKey });
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: [{ role: "user", parts: [{ text: `Generate social media promotion posts for a website generated by AI. Project Title: "${title}". User Prompt: "${prompt}". Return ONLY valid JSON: {"instagram": "caption with 5 hashtags", "twitter": "under 280 chars", "linkedin": "3-4 sentences"}` }] }],
      });
      
      let text = response.text || "{}";
      text = text.replace(/```json\n?/, "").replace(/```$/, "");
      setCaptions(JSON.parse(text));
    } catch (err) {
      console.error("Caption generation failed", err);
    } finally {
      setLoading(false);
    }
  };

  const drawGraphic = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    // Dimensions
    canvas.width = 1200;
    canvas.height = 630;

    // Background
    const gradient = ctx.createLinearGradient(0, 0, 1200, 630);
    gradient.addColorStop(0, "#0a0a0a");
    gradient.addColorStop(1, "#112222");
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, 1200, 630);

    // Accent glow
    const glow = ctx.createRadialGradient(600, 315, 0, 600, 315, 600);
    glow.addColorStop(0, "rgba(0, 255, 255, 0.15)");
    glow.addColorStop(1, "rgba(0, 255, 255, 0)");
    ctx.fillStyle = glow;
    ctx.fillRect(0, 0, 1200, 630);

    // Grid lines
    ctx.strokeStyle = "rgba(255, 255, 255, 0.05)";
    ctx.lineWidth = 1;
    for (let i = 0; i < 1200; i += 40) {
      ctx.beginPath();
      ctx.moveTo(i, 0);
      ctx.lineTo(i, 630);
      ctx.stroke();
    }
    for (let i = 0; i < 630; i += 40) {
      ctx.beginPath();
      ctx.moveTo(0, i);
      ctx.lineTo(1200, i);
      ctx.stroke();
    }

    // Title
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 80px Inter, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText(title || "Vora AI Project", 600, 280);

    // Prompt
    ctx.fillStyle = "rgba(255, 255, 255, 0.6)";
    ctx.font = "32px Inter, sans-serif";
    const truncatedPrompt = prompt.length > 60 ? prompt.substring(0, 60) + "..." : prompt;
    ctx.fillText(`"${truncatedPrompt}"`, 600, 350);

    // Brand
    ctx.fillStyle = "#00ffff";
    ctx.font = "bold 24px Inter, sans-serif";
    ctx.textAlign = "right";
    ctx.fillText("Built with Vora AI", 1150, 580);
  };

  const downloadGraphic = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    canvas.toBlob((blob) => {
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${title.replace(/\s+/g, '-').toLowerCase()}-launch.png`;
      a.click();
      URL.revokeObjectURL(url);
    });
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({ title: "Copied to clipboard" });
  };

  const shareTwitter = () => {
    if (!captions?.twitter) return;
    window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(captions.twitter)}`, "_blank");
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[700px] bg-background/95 backdrop-blur-xl border-border/50">
        <DialogHeader>
          <DialogTitle>Social Viral Kit</DialogTitle>
        </DialogHeader>
        
        <Tabs defaultValue="captions" className="w-full mt-4">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="captions">Captions</TabsTrigger>
            <TabsTrigger value="graphic">Launch Graphic</TabsTrigger>
          </TabsList>
          
          <TabsContent value="captions" className="mt-4 space-y-4">
            {loading ? (
              <div className="flex flex-col items-center justify-center py-12 text-muted-foreground">
                <Loader2 className="w-8 h-8 animate-spin mb-4 text-primary" />
                <p>Generating viral captions...</p>
              </div>
            ) : (
              <div className="space-y-4 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
                {captions?.twitter && (
                  <div className="p-4 rounded-xl border border-border/50 bg-card/50 space-y-3">
                    <div className="flex items-center justify-between text-sm font-medium text-muted-foreground">
                      X (Twitter)
                      <div className="flex gap-2">
                        <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => copyToClipboard(captions.twitter!)}><Copy className="w-4 h-4" /></Button>
                        <Button variant="ghost" size="icon" className="h-8 w-8 text-primary" onClick={shareTwitter}><Share2 className="w-4 h-4" /></Button>
                      </div>
                    </div>
                    <p className="text-sm">{captions.twitter}</p>
                  </div>
                )}
                
                {captions?.linkedin && (
                  <div className="p-4 rounded-xl border border-border/50 bg-card/50 space-y-3">
                    <div className="flex items-center justify-between text-sm font-medium text-muted-foreground">
                      LinkedIn
                      <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => copyToClipboard(captions.linkedin!)}><Copy className="w-4 h-4" /></Button>
                    </div>
                    <p className="text-sm whitespace-pre-wrap">{captions.linkedin}</p>
                  </div>
                )}

                {captions?.instagram && (
                  <div className="p-4 rounded-xl border border-border/50 bg-card/50 space-y-3">
                    <div className="flex items-center justify-between text-sm font-medium text-muted-foreground">
                      Instagram
                      <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => copyToClipboard(captions.instagram!)}><Copy className="w-4 h-4" /></Button>
                    </div>
                    <p className="text-sm whitespace-pre-wrap">{captions.instagram}</p>
                  </div>
                )}
              </div>
            )}
          </TabsContent>
          
          <TabsContent value="graphic" className="mt-4 space-y-4">
            <div className="rounded-xl border border-border/50 overflow-hidden bg-black flex items-center justify-center p-2">
              <canvas ref={canvasRef} className="w-full h-auto rounded-lg shadow-xl" style={{ aspectRatio: '1200/630' }} />
            </div>
            <Button className="w-full" onClick={downloadGraphic}>
              <Download className="w-4 h-4 mr-2" /> Download Graphic
            </Button>
          </TabsContent>
        </Tabs>

      </DialogContent>
    </Dialog>
  );
}
